### ISSUE TITLE
The link in "link.txt" has expired.

### ISSUE THREAD

**Issue by yjdfly** [aaronhd/pybullet_kinova7#2]
Hello, I am learning to train robotic arm agent in gym and your work is very meaningful to me, but the link in "link.txt" has expired, can you update it, thanks a lot!

**Comment by aaronhd** [comment]
The link is updated and I only find the model for greyd version. Please let me know if you have any other questions I can help.

**Comment by yjdfly** [comment]
**Thanks for your reply，I successfully downloaded model for greyd and urdfs. Then I want to see the effect of grasp random object, but when I ran the run_ugnet_greyd_pybullet.py and enjoy_kinova7_diverse_object_grasping.py, I got a mistake that I cannot solved at 'pred_out = model.predict(rgbd_input)', can you give me some advice. The errors are as follows**

> [ERROR] [1589288712.223133]: bad callback: <function depth_callback at 0x7f6a41d80578>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/robot/realsense_ws/src/ggcnn_kinova_grasping/ggcnn_kinova_grasping/scripts/pybullet_kinova7/run_ugnet_greyd_pybullet.py", line 235, in depth_callback
    pred_out = model.predict(rgbd_input)
  File "/home/robot/.local/lib/python2.7/site-packages/keras/engine/training.py", line 1169, in predict
    steps=steps)
  File "/home/robot/.local/lib/python2.7/site-packages/keras/engine/training_arrays.py", line 294, in predict_loop
    batch_outs = f(ins_batch)
  File "/home/robot/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2721, in __call__
    return self._legacy_call(inputs)
  File "/home/robot/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2693, in _legacy_call
    **self.session_kwargs)
  File "/home/robot/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/robot/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/robot/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/home/robot/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
FailedPreconditionError: Attempting to use uninitialized value conv2d_11/bias
         [[Node: conv2d_11/bias/read = Identity[T=DT_FLOAT, _class=["loc:@conv2d_11/bias"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](conv2d_11/bias)]]
         [[Node: cos_out_1/concat/_15 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_860_cos_out_1/concat", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op u'conv2d_11/bias/read', defined at:
  File "/home/robot/realsense_ws/src/ggcnn_kinova_grasping/ggcnn_kinova_grasping/scripts/pybullet_kinova7/run_ugnet_greyd_pybullet.py", line 45, in <module>
    model = load_model(MODEL_FILE)
  File "/home/robot/.local/lib/python2.7/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/home/robot/.local/lib/python2.7/site-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/robot/.local/lib/python2.7/site-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/robot/.local/lib/python2.7/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/robot/.local/lib/python2.7/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/robot/.local/lib/python2.7/site-packages/keras/engine/network.py", line 1022, in from_config
    process_layer(layer_data)
  File "/home/robot/.local/lib/python2.7/site-packages/keras/engine/network.py", line 1008, in process_layer
    custom_objects=custom_objects)
  File "/home/robot/.local/lib/python2.7/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/robot/.local/lib/python2.7/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/robot/.local/lib/python2.7/site-packages/keras/engine/network.py", line 1032, in from_config
    process_node(layer, node_data)
  File "/home/robot/.local/lib/python2.7/site-packages/keras/engine/network.py", line 991, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "/home/robot/.local/lib/python2.7/site-packages/keras/engine/base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/home/robot/.local/lib/python2.7/site-packages/keras/layers/convolutional.py", line 147, in build
    constraint=self.bias_constraint)
  File "/home/robot/.local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/robot/.local/lib/python2.7/site-packages/keras/engine/base_layer.py", line 252, in add_weight
    constraint=constraint)
  File "/home/robot/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 402, in variable
    v = tf.Variable(value, dtype=tf.as_dtype(dtype), name=name)
  File "/home/robot/.local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 235, in __init__
    constraint=constraint)
  File "/home/robot/.local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 391, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/home/robot/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 142, in identity
    return gen_array_ops.identity(input, name=name)
  File "/home/robot/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3053, in identity
    "Identity", input=input, name=name)
  File "/home/robot/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/robot/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/home/robot/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value conv2d_11/bias
         [[Node: conv2d_11/bias/read = Identity[T=DT_FLOAT, _class=["loc:@conv2d_11/bias"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](conv2d_11/bias)]]
         [[Node: cos_out_1/concat/_15 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_860_cos_out_1/concat", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by aaronhd** [comment]
I think it may be caused by keras version. It is noted that my model is trained on Tensorflow-GPU verison.

**Comment by yjdfly** [comment]
My environment is python=2.7 tensorflow_gpu=1.7 keras=2.2.4 cuda=9.0 cudnn=7.0.5, is this right?

**Comment by aaronhd** [comment]
I test the code from Github repository well. The **rgbd_used** set **True** for greyd model in enjoy_kinova7_diverse_object_grasping.py. You need to run roscore,  run_ugnet_greyd_pybullet.py. And until the model loading is completed ,  you can run enjoy_kinova7_diverse_object_grasping.py at last.  My cudnn=7.6, but I am not sure it caused the problem.

**Comment by yjdfly** [comment]
Thanks for your quick reply and update. I sincerely hope it didn't delay you too much. 
I have solved this problem refer to https://github.com/keras-team/keras/issues/4623#issuecomment-265982117 and the result is well.
what's more, could you tell me how to train a epoch_10_model for a new scence, new robot and new task?

**Comment by aaronhd** [comment]
Actually, this project is just my trail for RL environment last year and transfer the KUKA project to Kinova in Pybullet library example.  The model used here is my another work (https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8945792) to improve open-loop scheme in ggcnn in kinematics level .  You can train from scratch using Cornell dataset, Jacquard dataset or VMRD (humanoid) easily.

**Comment by aaronhd** [comment]
Actually, this project is just my trial for RL environment last year and transfers the KUKA project to Kinova in Pybullet library example. The model used here is my another work (https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8945792) to improve open-loop scheme in ggcnn in kinematics level . You can train from scratch using Cornell dataset, Jacquard dataset or VMRD (humanoid) easily.

**Comment by yjdfly** [comment]
Roger that，thanks！
